"""Update APIKey model for secure auth

Revision ID: 3ee567aba923
Revises: 2bbf297710c3
Create Date: 2025-08-29 01:24:28.268371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee567aba923'
down_revision: Union[str, Sequence[str], None] = '2bbf297710c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('public_id', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('hashed_secret', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('requests_per_minute_limit', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('api_keys_hashed_api_key_key'), 'api_keys', type_='unique')
    op.drop_constraint(op.f('api_keys_user_id_key'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_public_id'), 'api_keys', ['public_id'], unique=True)
    op.create_unique_constraint(None, 'api_keys', ['hashed_secret'])
    op.drop_column('api_keys', 'hashed_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('hashed_api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_public_id'), table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_user_id_key'), 'api_keys', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('api_keys_hashed_api_key_key'), 'api_keys', ['hashed_api_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'requests_per_minute_limit')
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'hashed_secret')
    op.drop_column('api_keys', 'public_id')
    # ### end Alembic commands ###
